stages:
  - format
  - test
  - deploy_stageing
  - deploy_prod

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: gradle-cache
  policy: pull-push
  paths:
    - .gradle/wrapper
    - .gradle/caches

format:
  stage: format
  image: gradle:8.6-jdk21-alpine
  script:
    - ./gradlew --build-cache --parallel spotlessCheck
  only:
    - merge_requests
    - main

unit_test:
  stage: test
  image: gradle:8.6-jdk21-alpine
  needs: ["format"]
  script:
    - ./gradlew --build-cache --parallel test
  artifacts:
    reports:
      junit: build/test-results/test/*.xml
    paths:
      - build
  only:
    - merge_requests
    - main

# 4. Notify Coolify webhook for redeploy
coolify_deploy_stageing:
  stage: deploy_stageing
  image: curlimages/curl:latest
  variables:
    AUTH_HEADER: "Authorization: Bearer $COOLIFY_TOK"
  script:
    - curl -X GET "$COOLIFY_STAGING_URL" -H "$AUTH_HEADER"
  only:
    - main

# 4. Notify Coolify webhook for redeploy
coolify_deploy_prod:
  stage: deploy_prod
  image: curlimages/curl:latest
  variables:
    AUTH_HEADER: "Authorization: Bearer $COOLIFY_TOK"
  script:
    - curl -X GET "$COOLIFY_PROD_URL" -H "$AUTH_HEADER"
  only:
    - production
