stages:
  - format
  - test
  - deploy_stageing
  - deploy_prod

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: gradle-cache
  policy: pull-push
  paths:
    - .gradle/wrapper
    - .gradle/caches

format:
  stage: format
  image: gradle:8.6-jdk21-alpine
  script:
    - ./gradlew --build-cache --parallel spotlessCheck
  only:
    - merge_requests

unit_test:
  stage: test
  image: gradle:8.6-jdk21-alpine
  needs: ["format"]  # keep if you have a formatting job
  script:
    # 1. Clean and run all checks (tests + coverage verification)
    - ./gradlew -build-cache --parallel test jacocoTestReport

    # 2. Parse JaCoCo CSV to print coverage to stdout for GitLab
    - >-
      awk -F"," '
      NR>1 { instructions += $4 + $5; covered += $5 } 
      END { if (instructions>0) printf "JaCoCo instructions covered: %.2f %%\n", 100 * covered / instructions }'
      build/reports/jacoco/test/jacocoTestReport.csv || true
  coverage: '/JaCoCo instructions covered: (\d+\.?\d*) %/'
  artifacts:
    when: always
    paths:
      - build
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    expire_in: 30 days
  only:
    - merge_requests

# 4. Notify Coolify webhook for redeploy
coolify_deploy_stageing:
  stage: deploy_stageing
  image: curlimages/curl:latest
  variables:
    AUTH_HEADER: "Authorization: Bearer $COOLIFY_TOK"
  script:
    - curl -X GET "$COOLIFY_STAGING_URL" -H "$AUTH_HEADER"
  only:
    - main

# 4. Notify Coolify webhook for redeploy
coolify_deploy_prod:
  stage: deploy_prod
  image: curlimages/curl:latest
  variables:
    AUTH_HEADER: "Authorization: Bearer $COOLIFY_TOK"
  script:
    - curl -X GET "$COOLIFY_PROD_URL" -H "$AUTH_HEADER"
  only:
    - production
