plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '6.22.0'
}

group = 'ch.bbcag'
version = '0.0.1-SNAPSHOT'
description = 'Wrodit-Backend'

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}
spotless {
    java {
        googleJavaFormat('1.17.0') // or choose your preferred formatter
    }
}
dependencies {
    // Spring dependencies
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Spring Security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // MySQL driver
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Dev tools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

tasks.named('test') {
    useJUnitPlatform()
}